#!/usr/bin/env python3
"""Nexus Agent — an ultra-light metrics endpoint for ANY Linux machine, so the
Nexus Controller can monitor hosts that don't run a full Nexus Dashboard.

Design:
  * **stdlib only** — no pip, no venv, no compiled deps. Runs on the system
    python3 of any distro.
  * **Read-only by construction** — there are no write endpoints. It reads
    /proc and statvfs()s mounted filesystems; nothing more. Runs as an
    unprivileged dedicated user under a hardened systemd unit (see install.sh).
  * **One authed endpoint**: ``GET /api/v1/metrics`` with
    ``Authorization: Bearer <token>`` → up/down (implicit), CPU %, memory,
    and per-mount storage utilization. ``GET /`` answers a tiny unauthed
    identity blob (healthchecks / humans).
  * **HTTPS** with a self-signed cert (generated by install.sh); the
    controller TOFU-pins the fingerprint at enroll, verified in-handshake on
    every poll — same trust model as a full dashboard node.
  * A background sampler computes the CPU percentage (/proc/stat delta) and
    refreshes the mount table, so a request never blocks on a hung network
    mount — the handler only ever serves the last snapshot.

Config (env, set by the systemd unit): AGENT_PORT (default 9143), AGENT_BIND,
AGENT_DATA_DIR (token + certs), AGENT_TLS=0 to serve plain HTTP behind a
TLS-terminating proxy.
"""
import os
import ssl
import json
import time
import hmac
import socket
import secrets
import threading
from http.server import ThreadingHTTPServer, BaseHTTPRequestHandler

AGENT_VERSION = '1.0.0'

APP_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.environ.get('AGENT_DATA_DIR', os.path.join(APP_DIR, 'data'))
PORT = int(os.environ.get('AGENT_PORT', '9143'))
BIND = os.environ.get('AGENT_BIND', '0.0.0.0')
TLS_ENABLED = os.environ.get('AGENT_TLS', '1').lower() in ('1', 'true', 'yes', 'on')
TOKEN_FILE = os.environ.get('AGENT_TOKEN_FILE', os.path.join(DATA_DIR, 'token'))
TLS_CERT = os.environ.get('AGENT_TLS_CERT', os.path.join(DATA_DIR, 'agent.crt'))
TLS_KEY = os.environ.get('AGENT_TLS_KEY', os.path.join(DATA_DIR, 'agent.key'))
SAMPLE_INTERVAL = float(os.environ.get('AGENT_SAMPLE_INTERVAL', '5'))

# Pseudo/ephemeral filesystems that aren't "mounted storage".
SKIP_FSTYPES = {
    'proc', 'sysfs', 'devtmpfs', 'devpts', 'tmpfs', 'cgroup', 'cgroup2',
    'pstore', 'bpf', 'securityfs', 'debugfs', 'tracefs', 'configfs',
    'fusectl', 'mqueue', 'hugetlbfs', 'autofs', 'binfmt_misc', 'nsfs',
    'efivarfs', 'ramfs', 'squashfs', 'overlay', 'aufs', 'fuse.gvfsd-fuse',
    'fuse.portal', 'fuse.lxcfs', 'rpc_pipefs', 'selinuxfs', 'sunrpc',
}


# ─── Pure parsers (unit-tested) ───────────────────────────────────────
def parse_proc_stat(text):
    """First 'cpu ' line of /proc/stat → (idle_ticks, total_ticks)."""
    for line in (text or '').splitlines():
        if line.startswith('cpu '):
            f = [int(x) for x in line.split()[1:]]
            idle = f[3] + (f[4] if len(f) > 4 else 0)   # idle + iowait
            return idle, sum(f)
    return None


def cpu_percent(prev, cur):
    """Busy % between two parse_proc_stat samples (None until 2 samples)."""
    if not prev or not cur:
        return None
    didle, dtotal = cur[0] - prev[0], cur[1] - prev[1]
    if dtotal <= 0:
        return None
    return round(max(0.0, min(100.0, 100.0 * (1 - didle / dtotal))), 1)


def parse_meminfo(text):
    """/proc/meminfo → {'total','available','used','percent'} in bytes."""
    kv = {}
    for line in (text or '').splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[0].endswith(':'):
            kv[parts[0][:-1]] = int(parts[1]) * 1024   # kB → bytes
    total = kv.get('MemTotal') or 0
    avail = kv.get('MemAvailable')
    if avail is None:   # ancient kernels: approximate
        avail = (kv.get('MemFree') or 0) + (kv.get('Cached') or 0)
    used = max(0, total - avail)
    return {'total': total, 'available': avail, 'used': used,
            'percent': round(used / total * 100, 1) if total else None}


def parse_mounts(text):
    """/proc/mounts → [(device, mountpoint, fstype)] of real storage mounts,
    deduped by device (bind mounts keep the shortest mountpoint)."""
    seen = {}   # device -> (mountpoint, fstype)
    for line in (text or '').splitlines():
        parts = line.split()
        if len(parts) < 3:
            continue
        dev, mp, fst = parts[0], parts[1].replace('\\040', ' '), parts[2]
        if fst in SKIP_FSTYPES or fst.startswith(('fuse.gvfs', 'cgroup')):
            continue
        if mp.startswith(('/proc', '/sys', '/dev', '/run/user', '/snap',
                          '/var/lib/docker/', '/var/snap')):
            continue
        if dev in seen and len(seen[dev][0]) <= len(mp):
            continue
        seen[dev] = (mp, fst)
    return [(dev, mp, fst) for dev, (mp, fst) in seen.items()]


def mount_usage(entries, statvfs=os.statvfs):
    """statvfs each mount → usage dicts (skips empty/broken ones)."""
    out = []
    for dev, mp, fst in entries:
        try:
            st = statvfs(mp)
        except OSError:
            continue
        total = st.f_blocks * st.f_frsize
        if not total:
            continue
        free = st.f_bfree * st.f_frsize
        used = total - free
        out.append({'device': dev, 'mountpoint': mp, 'fstype': fst,
                    'total': total, 'used': used, 'free': free,
                    'percent': round(used / total * 100, 1)})
    out.sort(key=lambda m: m['mountpoint'])
    return out


def os_release():
    try:
        with open('/etc/os-release') as f:
            for line in f:
                if line.startswith('PRETTY_NAME='):
                    return line.split('=', 1)[1].strip().strip('"')
    except OSError:
        pass
    return None


# ─── Sampler (CPU delta + mount snapshot; never blocks a request) ─────
_state = {'cpu_percent': None, 'mounts': [], 'sampled_at': 0.0}
_state_lock = threading.Lock()


def _read(path):
    try:
        with open(path) as f:
            return f.read()
    except OSError:
        return ''


def _sampler_loop():
    prev = parse_proc_stat(_read('/proc/stat'))
    while True:
        time.sleep(SAMPLE_INTERVAL)
        try:
            cur = parse_proc_stat(_read('/proc/stat'))
            pct = cpu_percent(prev, cur)
            prev = cur
            mounts = mount_usage(parse_mounts(_read('/proc/mounts')))
            with _state_lock:
                _state['cpu_percent'] = pct
                _state['mounts'] = mounts
                _state['sampled_at'] = time.time()
        except Exception:
            pass   # a bad cycle must never kill the sampler


def build_metrics():
    with _state_lock:
        cpu_pct, mounts = _state['cpu_percent'], list(_state['mounts'])
        sampled_at = _state['sampled_at']
    try:
        load1 = os.getloadavg()[0]
    except OSError:
        load1 = None
    up = _read('/proc/uptime').split()
    uname = os.uname()
    return {
        'agent': 'nexus-agent',
        'version': AGENT_VERSION,
        'platform': 'linux',
        'hostname': socket.gethostname(),
        'os': os_release(),
        'kernel': uname.release,
        'arch': uname.machine,
        'uptime_seconds': int(float(up[0])) if up else None,
        'sampled_at': sampled_at,
        'cpu': {'percent': cpu_pct, 'count': os.cpu_count(),
                'load1': round(load1, 2) if load1 is not None else None},
        'memory': parse_meminfo(_read('/proc/meminfo')),
        'mounts': mounts,
    }


# ─── HTTP server ──────────────────────────────────────────────────────
_token = None


class Handler(BaseHTTPRequestHandler):
    server_version = 'nexus-agent/' + AGENT_VERSION

    def _json(self, obj, code=200):
        body = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header('Content-Type', 'application/json')
        self.send_header('Content-Length', str(len(body)))
        self.end_headers()
        self.wfile.write(body)

    def _authed(self):
        h = self.headers.get('Authorization', '')
        supplied = h[7:].strip() if h.lower().startswith('bearer ') else ''
        return bool(supplied) and hmac.compare_digest(supplied, _token)

    def do_GET(self):
        path = self.path.split('?', 1)[0].rstrip('/') or '/'
        if path == '/':
            return self._json({'app': 'nexus-agent', 'version': AGENT_VERSION})
        if path in ('/api/v1/metrics', '/metrics'):
            if not self._authed():
                return self._json({'error': 'authentication required'}, 401)
            return self._json(build_metrics())
        return self._json({'error': 'not found'}, 404)

    def log_message(self, fmt, *args):   # journal stays quiet on the 15s polls
        pass


def _load_token():
    """Read the bearer token; self-mint one on first run (printed once)."""
    try:
        tok = open(TOKEN_FILE).read().strip()
        if tok:
            return tok
    except OSError:
        pass
    tok = 'na_' + secrets.token_urlsafe(32)
    os.makedirs(DATA_DIR, exist_ok=True)
    fd = os.open(TOKEN_FILE, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, 'w') as f:
        f.write(tok + '\n')
    print('nexus-agent: minted new API token (enroll the host with it):', flush=True)
    print('  ' + tok, flush=True)
    return tok


def main():
    global _token
    _token = _load_token()
    httpd = ThreadingHTTPServer((BIND, PORT), Handler)
    if TLS_ENABLED:
        if not (os.path.exists(TLS_CERT) and os.path.exists(TLS_KEY)):
            raise SystemExit(f'nexus-agent: missing TLS cert/key ({TLS_CERT}, '
                             f'{TLS_KEY}) — run install.sh, or set AGENT_TLS=0 '
                             'behind a TLS proxy')
        ctx = ssl.SSLContext(ssl.PROTOCOL_TLS_SERVER)
        ctx.load_cert_chain(TLS_CERT, TLS_KEY)
        httpd.socket = ctx.wrap_socket(httpd.socket, server_side=True)
    threading.Thread(target=_sampler_loop, daemon=True, name='sampler').start()
    print(f'nexus-agent v{AGENT_VERSION} on '
          f'{"https" if TLS_ENABLED else "http"}://{BIND}:{PORT}', flush=True)
    httpd.serve_forever()


if __name__ == '__main__':
    main()
